spring:
  session:
    store-type: redis
    redis.namespace: demo:spring:session
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 0
    password: ${REDIS_PWD}



logging:
  level:
    org.springframework.security: debug