spring:
  session:
    store-type: redis
    redis.namespace: demo:spring:session
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: 0
    password: ${REDIS_PWD}


logging:
  level:
    org.springframework.security: debug